# https://github.com/elsonrodriguez/spark-ui-proxy
# https://github.com/aseigneurin/spark-ui-proxy

---

apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: spark-standalone
spec:
  type: ClusterIP
  selector:
    app: spark
    component: spark-ui-proxy
  ports:
  - port: 80
    targetPort: 80
    
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spark-ui-proxy
  namespace: spark-standalone
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spark
      component: spark-ui-proxy
  template:
    metadata:
      labels:
        app: spark
        component: spark-ui-proxy
    spec:
      # depends_on
      initContainers:
      - name: check-master-health
        image: busybox:1
        command: ["/bin/sh", "-c", "nslookup master-hs"]
      containers:
      - name: spark-ui
        image:  elsonrodriguez/spark-ui-proxy:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: proxy
          containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        args:
        - master-hs:8080