# 仅限：nvidia-docker2 + nvidia-device-plugin（不设置 resources.limits["nvidia.com/gpu"] 将使用主机的所有 GPU）
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ethminer
  namespace: ethereum
spec:
  selector:
    matchLabels:
      app: ethminer
  template:
    metadata:
      labels:
        app: ethminer
    spec:
      nodeSelector:
        node-type: gpu
        nvidia.com/gpu-name: "p106-100"
      containers:
      - name: ethminer
        image: dockerce/cuda-ethminer:9.1-0.12.0
        imagePullPolicy: IfNotPresent
        command: ["ethminer"]
        args:
        - -U 
        - -F
        - http://ethproxy.ethereum.svc.cluster.local:8080/$(HOST_IP)
        - --farm-recheck
        - "100"
        # - -SP
        # - "1"
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 320Mi
        readinessProbe:
          exec:
            command:
            - pgrep
            - ethminer
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pgrep
            - ethminer
          initialDelaySeconds: 5
          periodSeconds: 5