apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: database
  labels:
    name: redis-sentinel
spec:
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    redis-sentinel: "true"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: database
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        redis-sentinel: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: gcr.io/google_containers/redis:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis-sentinel
          containerPort: 26379
        env:
        - name: SENTINEL
          value: "true"