apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: hadoop
  labels:
    app: datanode
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: datanode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: datanode
  namespace: hadoop
spec:
  serviceName: datanode
  replicas: 1
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: hdfs:2.7.3
        volumeMounts:
        - name: config
          mountPath: "/opt/hadoop/etc/hadoop"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: hadoopconf