apiVersion: v1
kind: Secret
metadata:
  name: rbd-secret-admin
  namespace: kube-system # 其他命名空间可以共享 kube-system 命名空间的资源
type: kubernetes.io/rbd # This is required for Ceph RBD to work with dynamic provisioning.
data:
  key: QVFBUGo3ZFpCMk5jTlJBQW5ZNVdNM1NLQzhldVA5d3JJajBvWFE9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rbd-secret-admin # 每个命名空间都需要创建一个与 StorageClass 的 parameters.adminSecretName 同名的 Secret
  namespace: hadoop
type: kubernetes.io/rbd
data:
  key: QVFBUGo3ZFpCMk5jTlJBQW5ZNVdNM1NLQzhldVA5d3JJajBvWFE9PQ==