apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: gitlab
data:
  gitlab.rb: |
    external_url 'http://gitlab-ce.gitlab.svc.cluster.local:80'
    gitlab_rails['gitlab_shell_ssh_port'] = 22
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'
    gitlab_rails['smtp_port'] = 25
    gitlab_rails['smtp_user_name'] = 'logs@eway.link'
    gitlab_rails['smtp_password'] = 'Ab123456'
    gitlab_rails['smtp_domain'] = 'smtp.qq.com'
    gitlab_rails['smtp_authentication'] = 'login'
    gitlab_rails['smtp_tls'] = false
    gitlab_rails['gitlab_email_from'] = 'logs@eway.link'
    user['git_user_email'] = 'logs@eway.link'
    gitlab_rails['initial_root_password'] = "Yinrenqiang123"