apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: dockerce/spark:2.3.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        env:
        - name: SPARK_WORKER_PORT
          value: "7078"
        - name: SPARK_WORKER_CORES
          valueFrom:  # Integer, examples: '1', '3'
            resourceFieldRef:
              resource: requests.cpu
        - name: SPARK_WORKER_MEMORY
          valueFrom:  # Integer, examples: '1024m', '1g'
            resourceFieldRef:
              resource: requests.memory
        ports:
        - name: webui
          containerPort: 8081
        - name: worker-port
          containerPort: 7078
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        args: ["start-worker", "spark://master:7077"]