apiVersion: v1
kind: Secret
metadata:
  name: rbd-secret-admin # 每个命名空间都需要创建一个与 StorageClass 的 parameters.adminSecretName 同名的 Secret
  namespace: ns1
type: kubernetes.io/rbd
data:
  key: QVFBUGo3ZFpCMk5jTlJBQW5ZNVdNM1NLQzhldVA5d3JJajBvWFE9PQ==