# kubectl -n ckad run nginx --image=nginx --replicas=2
# kubectl -n ckad expose deployment nginx --port=80
# kubectl -n ckad get svc,pod
# kubectl -n ckad run busybox --rm -ti --image=busybox -- /bin/sh -c "wget --spider --timeout=1 nginx"
# kind: NetworkPolicy
# apiVerion: networking.k8s.io/v1
# metadata:
#   name: access-nginx
#   namespace: ckad
# spec:
#   podSelector:
#     matchLabels:
#       run: nginx
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels:
#           access: "true"

cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: kdsn00201
spec:
  podSelector:
    matchLabels:
      name: kdsn00201-newpod
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: www
    - podSelector:
        matchLabels:
          name: api
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: www
    - podSelector:
        matchLabels:
          name: api
EOF

cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
  namespace: ckad
spec:
  podSelector:
    matchLabels:
      name: kdsn00201-newpod
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: www
    - podSelector:
        matchLabels:
          name: api
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: www
    - podSelector:
        matchLabels:
          name: api
EOF