
cat <<EOF | kubectl -n ckad apply -f -
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
EOF

for ns in ckad; do
  allPods=$(kubectl -n $ns get pod | awk 'FNR > 1 {print $1}')

  for pod in ${allPods[@]}; do
    unhealthy=$(kubectl -n $ns describe pod $pod | grep 'Events:' -A 100 | awk 'FNR > 3 {print $2}' | grep 'Unhealthy')
    unhealthyEvent=$(kubectl -n $ns describe pod $pod | grep "Events:" -A 100 | grep 'Unhealthy')
    if [ -n "$unhealthy" ]; then
      echo "$ns/$pod" >> broken.txt
      echo "$ns/$pod | $unhealthyEvent" >> error.txt
    fi
  done
done

for ns in qa test production alan; do
  allPods=$(kubectl -n $ns get pod | awk 'FNR > 1 {print $1}')

  for pod in ${allPods[@]}; do
    unhealthy=$(kubectl -n $ns describe pod $pod | grep 'Events:' -A 100 | awk 'FNR > 3 {print $2}' | grep 'Unhealthy')
    unhealthyEvent=$(kubectl -n $ns describe pod $pod | grep "Events:" -A 100 | grep 'Unhealthy')
    if [ -n "$unhealthy" ]; then
      echo "$ns/$pod" >> broken.txt
      echo "$ns/$pod | $unhealthyEvent" >> error.txt
    fi
  done
done