apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  storageClassName: hostvol
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/opt/KDSP00101/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: hostvol
  requests:
    resource:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
---
kind: kind: Pod
apiVersion: v1
metadata:
  name: my-storage-app
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: task-pv-claim

