apiVersion: v1
kind: Pod
metadata:
  name: redis-server
  namespace: redis
  labels:
    name: redis-server
spec:
  containers:
  - name: redis-server
    image: lfccncf/redis:3.2
    ports:
      - containerPort: 6379