# 并没有使用
kind: Service
apiVersion: v1
metadata:
  name: namenode
  namespace: hdfs
spec:
  selector:
    app: hdfs
    component: namenode
  ports:
  - name: ipc
    port: 9000
    targetPort: 9000
  - name: webui
    port: 50070
    targetPort: 50070