apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-porxy
  namespace: docker-registry
spec:
  template:
    metadata:
      name: registry-porxy
      labels:
        app: registry-porxy
    spec:
      hostNetwork: true
      containers:
      - name: registry-porxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: REGISTRY_HOST
          value: registry-swift.docker-registry.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: proxy
          containerPort: 80
          hostPort: 5000