apiVersion: v1
kind: Secret
metadata:
  name: registry-swift
  namespace: docker-registry
type: Opaque
data:
  # echo -n "http://192.168.10.201:7480/auth/v1" | base64
  storage.swift.authurl: "aHR0cDovLzE5Mi4xNjguMTAuMjAxOjc0ODAvYXV0aC92MQ=="
  # echo -n "dockerregistry:swift" | base64
  storage.swift.username: "ZG9ja2VycmVnaXN0cnk6c3dpZnQ="
  # echo -n "lVX2yvKzozeCynSuDodTqBFwN6wGwEerJPUgogZc" | base64
  storage.swift.password: "bFZYMnl2S3pvemVDeW5TdURvZFRxQkZ3TjZ3R3dFZXJKUFVnb2daYw=="
  # echo -n "registry" | base64
  storage.swift.container: "cmVnaXN0cnk="