apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: yarn
  labels:
    app: resourcemanager
spec:
  type: ClusterIP
  selector:
    app: resourcemanager
  ports:
  - name: scheduler
    port: 8030
    targetPort: 8030
  - name: resource-tracker
    port: 8031
    targetPort: 8031
  - name: resourcemanager
    port: 8032
    targetPort: 8032
  - name: admin
    port: 8032
    targetPort: 8033
  - name: webapp
    port: 8088
    targetPort: 8088