apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  # echo -n "postgres" | base64
  postgres.user: "cG9zdGdyZXM="
  postgres.password: "cG9zdGdyZXMxMjM0NTY="