apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
  namespace: database
spec:
  selector:
    app: redis-sentinel
  ports:
  - port: 26379
    targetPort: 26379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
  namespace: database
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: sentinel
        image: gcr.io/google_containers/redis:v1
        ports:
        - containerPort: 26379
        env:
        - name: SENTINEL
          value: "true"