apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
  namespace: database
spec:
  selector:
    app: redis-master
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-master
  namespace: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: master
        image: gcr.io/google_containers/redis:v1
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        volumeMounts:
        - name: redis-master-config
          mountPath: /redis-master
      volumes:
      - name: redis-master-config
        configMap:
          name: redis-config
          items:
          - key: redis-master.conf
            path: ./redis.conf
