apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
  namespace: cassandra-cluster
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
  - name: cql
    port: 9042
    targetPort: 9042