apiVersion: v1
kind: Service
metadata:
  name: kafka-discovery
  namespace: kafka-cluster
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: server
    port: 9092
    targetPort: 9092
    nodePort: 9092