apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: hadoop
  labels:
    app: datanode
spec:
  clusterIP: None
  ports:
  - name: http
    port: 50075
    targetPort: 50075
  - name: data-transfer
    port: 50010
    targetPort: 50010
  - name: ipc
    port: 50020
    targetPort: 50020
  selector:
     app: datanode